config/routes.rb
LinkedinProfiles::Application.routes.draw do
  devise_for :users,path_names: {:sign_in => 'login', :sign_up => 'register', :sign_out => 'logout'},:controllers => {:sessions=>"users/sessions",:passwords => "users/passwords"}
  resources :linkedin_scarpers
  get 'provide_linkedin_profile' => 'linkedin_scarpers#get_profile_link', :as => :new_profile
  root 'linkedin_scarpers#index'

end

app/models/linkedin_scarper.rb
class LinkedinScarper < ActiveRecord::Base
serialize :organization,Array
serialize :websites,Array
serialize :education,Array
serialize :groups,Array
serialize :languages,Array
serialize :certifications,Array
serialize :current_companies,Array
serialize :recommended_visitors,Array
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/linkedin_scarpers_controller.rb
class LinkedinScarpersController < ApplicationController
  before_action :set_linkedin_scarper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /linkedin_scarpers
  # GET /linkedin_scarpers.json
  def index
    @linkedin_scarpers = LinkedinScarper.all.page(params[:page]).per(10)
  end

  # GET /linkedin_scarpers/1
  # GET /linkedin_scarpers/1.json
  def show
  end

  # GET /linkedin_scarpers/new
  def new
    @linkedin_scarper = LinkedinScarper.new
  end

  # GET /linkedin_scarpers/1/edit
  def edit
  end

  # POST /linkedin_scarpers
  # POST /linkedin_scarpers.json
  def create
   if params[:linkedin_scarper][:profile_link].present?
   
    @profile_link =  Linkedin::Profile.get_profile(params[:linkedin_scarper][:profile_link])
    logger.warn(@profile_link.inspect)
    @linkedin_scarper = LinkedinScarper.new
    @linkedin_scarper.first_name   =  @profile_link.first_name   
    @linkedin_scarper.last_name    = @profile_link.last_name  
    @linkedin_scarper.name         = @profile_link.name  
    @linkedin_scarper.title        = @profile_link.title  
    @linkedin_scarper.summary      = @profile_link.summary 
    @linkedin_scarper.location     = @profile_link.location 
    @linkedin_scarper.country      = @profile_link.country 
    @linkedin_scarper.industry     = @profile_link.industry   
    @linkedin_scarper.picture      = @profile_link.picture 
    @linkedin_scarper.skills       = @profile_link.skills 
    @linkedin_scarper.organization = @profile_link.organizations 
    @linkedin_scarper.education    = @profile_link.education 
    @linkedin_scarper.websites     = @profile_link.websites 
    @linkedin_scarper.groups       = @profile_link.groups 
    @linkedin_scarper.languages    = @profile_link.groups 
    @linkedin_scarper.certifications  = @profile_linkcertifications  
    @linkedin_scarper.current_companies = @profile_link.current_companies 
    @linkedin_scarper.recommended_visitors = @profile_link.recommended_visitors
    

    respond_to do |format|
      if @linkedin_scarper.save
        format.html { redirect_to @linkedin_scarper, notice: 'Linkedin scarper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @linkedin_scarper }
      else
        format.html { render action: 'new' }
        format.json { render json: @linkedin_scarper.errors, status: :unprocessable_entity }
      end
    end
    else
     flash[:notice] ="Please Provide Link"
     redirect_to :back
    end
  end

  # PATCH/PUT /linkedin_scarpers/1
  # PATCH/PUT /linkedin_scarpers/1.json
  def update
    respond_to do |format|
      if @linkedin_scarper.update(linkedin_scarper_params)
        format.html { redirect_to @linkedin_scarper, notice: 'Linkedin scarper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @linkedin_scarper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkedin_scarpers/1
  # DELETE /linkedin_scarpers/1.json
  def destroy
    @linkedin_scarper.destroy
    respond_to do |format|
      format.html { redirect_to linkedin_scarpers_url }
      format.json { head :no_content }
    end
  end
  
  def get_profile_link
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linkedin_scarper
      @linkedin_scarper = LinkedinScarper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linkedin_scarper_params
      params.require(:linkedin_scarper).permit(:first_name, :last_name, :name, :title, :location, :country, :industry, :picture, :skills, :organization, :education, :websites, :groups, :languages, :certifications, :current_companies, :past_companies, :recommended_visitors)
    end
    
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
	layout 'login_layout'
	def new
		super
	end
	def create
    super
  end

  def edit
  	super
  end

  def update
  	super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	layout 'login_layout'
	def new
		super
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def edit_link(link_href , btnklass='btn btn-warning')
    link_to link_href, :class => "#{btnklass}"  do
      ("Edit " + (content_tag :i, "", :class => "icon-edit icon-white")).html_safe
    end
  end

  def view_link(link_href)
    link_to link_href, :class => "btn btn-info" do
       ("View "+(content_tag :i, "", :class => "icon-circle-arrow-right")).html_safe 
    end
  end

  def delete_link(link_href)
    link_to link_href, :method => :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do
      ("Delete "+(content_tag :i, "", :class => "icon-trash icon-white")).html_safe
    end
  end

  def button_link(name, link_href, klass, btnklass='btn mini')
    link_to link_href, :class => "#{btnklass}" do
      ("#{name} "+(content_tag :i, "", :class => "#{klass} icon-white")).html_safe
    end
  end

  def add_link(name,link_href)
    link_to link_href, :class => "btn" do
      (content_tag :i, "", :class => "icon-plus") + " #{name} "
    end
  end
  
  def show_inline_errors(errors_arr,column_field_arr)
    error_string = ""
    column_field_arr.each do |column_name|
      error_string += errors_arr[column_name].first if errors_arr[column_name].present?
    end
    error_string
  end

  def find_country(code)
    ISO3166::Country::Names.rassoc(code)[0]
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/linkedin_scarpers_helper.rb
module LinkedinScarpersHelper
end

app/helpers/login_layout_helper.rb
module LoginLayoutHelper
  def back_link(link_href)
    link_to link_href, :class => "btn" do
      (content_tag :i, "", :class => "m-icon-swapleft") + "Back"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- BEGIN FOOTER -->
<div class="footer">
  <div class="footer-inner">
		2013 &copy; BuilderApp
	</div>
	<div class="footer-tools">
		<span class="go-top">
		  <i class="icon-angle-up"></i>
		</span>
	</div>
</div>
	<!-- END FOOTER -->

app/views/layouts/_page_sidebar.html.erb
<!-- BEGIN EMPTY PAGE SIDEBAR -->
  <div class="page-sidebar nav-collapse collapse visible-phone visible-tablet">
    <ul class="page-sidebar-menu">
      <li class="<%= 'active' if controller.controller_name == 'dashboard' %>">
        <a href='<%= root_path %>'>
          Dashboard                        
        </a>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'properties' %>">
        <a href='<%=properties_path%>'>
          Properties
        </a>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'users' %>">
        <a href='<%=users_path%>'>Users</a>
      </li>
    </ul>
  </div>
<!-- END EMPTY PAGE SIDEBAR -->

app/views/layouts/_sidebar_menu.html.erb
   <aside id="sidebar">
                <!-- START Sidebar Content -->
                <div class="sidebar-content">
                    <!-- START Sidebar Tab -->

                    <!-- START Tab Content -->
                    <div class="tab-content">
                        <!-- START Tab Pane(menu) -->
                        <div class="tab-pane active" id="tab-menu">
                            <!-- START Sidebar Menu -->
                            <nav id="nav" class="accordion">
                                <ul id="navigation">
                                    <!-- START Menu Divider -->
                                    <li class="divider">Main Menu</li>
                                    <!--/ END Menu Divider -->

                                    <!-- START Menu -->
                                    <li class="accordion-group ">
                                        <a href="<%=root_path%>">
                                            <span class="icon icone-dashboard"></span>
                                            <span class="text">Scraped Profiles</span>
 
                                        </a>
                                    </li>
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    <li class=""accordion-group "">
                                         <a href="<%= new_profile_path %>">
                                            <span class="icon icone-bar-chart"></span>
                                            <span class="text">Scrape New Linkedin Profile</span>
                                           
                                        </a>
  
                                    </li>
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    <li class="accordion-group ">
                                        <a href="<%#= users_path %>">
                                            <span class="icon icone-user"></span>
                                            <span class="text">Users</span>
                                         
                                        </a>
                                        
                                    </li>
                                 
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    
                        </div>
                        <!--/ END Tab Pane(overview) -->
                    </div>
                    <!--/ END Tab Content -->
                </div>
                <!--/ END Sidebar Content -->
            </aside>

app/views/layouts/_top_header.html.erb
 <header id="header">
                <!-- START Logo -->
                <div class="logo hidden-phone hidden-tablet">
                    <a href="<%= root_path %>"><img src="/assets/rails.png" alt=""></a>
                    <small class="version"></small>
                </div>
                <!--/ END Logo -->

                <!-- START Mobile Sidebar Toggler -->
                <a href="<%= root_path %>" class="toggler" data-toggle="sidebar"><span class="icon icone-reorder"></span></a>
                <!--/ END Mobile Sidebar Toggler -->

                <!-- START Toolbar -->
                <ul class="toolbar" id="toolbar">
                    


                    <!-- START Profile -->
                    <li class="profile">
                        <a href="#" data-toggle="dropdown">
                            <span class="avatar"><img src="" alt=""></span>
                            <span class="text hidden-phone">Admin<span class="role"><%= current_user.email%></span></span>
                            <span class="arrow icone-caret-down"></span>
                        </a>
                        <!-- START Dropdown Menu -->
                        <div class="dropdown-menu" role="menu">
                            <header>
                                Your Profile 
                            </header>
                            <ul class="body">
                                <li>
                                    <a href="<%= edit_user_registration_path%>"><i class="icon-tasks"></i> Change Password</a>
                                </li>
                      
                       
                            </ul>
                            <footer>
                                <a href="<%= destroy_user_session_path%>" class="text" data-method='delete'><span class="icon icone-off"></span> Sign Off</a>
                            </footer>
                        </div>
                        <!--/ END Dropdown Menu -->
                    </li>
                    <!--/ END Profile -->
                </ul>
                <!--/ END Toolbar -->
            </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkedin scraper</title>
    <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  <script>
    jQuery(document).ready(function() {    
       App.init();
    });
  </script>
    
  </head>
  
  <body class="page-header-fixed page-full-width">
    <%= render :partial => "layouts/top_header" %>
   
    
    <!-- BEGIN CONTAINER -->   
    <div class="page-container row-fluid" >
     <%= render :partial => "layouts/sidebar_menu" %>
    <!-- BEGIN PAGE -->
     <section id="main">
                <!-- START Bootstrap Navbar -->
                <div class="navbar navbar-static-top">
                    <div class="navbar-inner">
                        <!-- Breadcrumb -->
                        <ul class="breadcrumb">
              <li>
                <%#=breadcrumbs%>
              </li>
              </ul>
              <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
          </div>
          <!-- END PAGE HEADER-->
          <!-- BEGIN PAGE CONTENT-->
          <div class="container-fluid">
                    <!-- START Row -->
                    <div class="row-fluid">
              <% flash.each do |key, message| %>
                <div id="flash_<%= key %>" class="alert"><%= message %></div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <!-- END PAGE CONTENT-->
        </div>
        <!-- END PAGE CONTAINER--> 
      </div>
      <!-- END PAGE -->    
    </div>
    <!-- END CONTAINER --> 
    <%= yield :scripts %>   
    <%= render :partial => "layouts/footer" %>
    </div>
    </div>
  </body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkedin scraper</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application"  %>
    <%= csrf_meta_tags %>
  </head>
   <div id="wrapper">
    <!-- START Template Canvas -->
    <div id="canvas">
      <!-- START Themer -->
      <!-- You can remove this. For demo purpose only -->
      <div class="container-fluid">
        <!-- START Row -->
        <div class="row-fluid">
          <!-- START Login Widget Form -->
          <link rel="shortcut icon" href="/favicon.ico" />
          <p>&nbsp;</p>
          <% flash.each do |key, message| %>
            <div id="flash_<%= key %>" class="alert"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
    </div>
  </div>
</div>
  </body>
</html>

app/views/linkedin_scarpers/_form.html.erb
<%= form_for(@linkedin_scarper) do |f| %>
  <% if @linkedin_scarper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linkedin_scarper.errors.count, "error") %> prohibited this linkedin_scarper from being saved:</h2>

      <ul>
      <% @linkedin_scarper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_area :organization %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_area :education %>
  </div>
  <div class="field">
    <%= f.label :websites %><br>
    <%= f.text_area :websites %>
  </div>
  <div class="field">
    <%= f.label :groups %><br>
    <%= f.text_area :groups %>
  </div>
  <div class="field">
    <%= f.label :languages %><br>
    <%= f.text_area :languages %>
  </div>
  <div class="field">
    <%= f.label :certifications %><br>
    <%= f.text_area :certifications %>
  </div>
  <div class="field">
    <%= f.label :current_companies %><br>
    <%= f.text_area :current_companies %>
  </div>
  <div class="field">
    <%= f.label :past_companies %><br>
    <%= f.text_area :past_companies %>
  </div>
  <div class="field">
    <%= f.label :recommended_visitors %><br>
    <%= f.text_area :recommended_visitors %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkedin_scarpers/edit.html.erb
<h1>Editing linkedin_scarper</h1>

<%= render 'form' %>

<%= link_to 'Show', @linkedin_scarper %> |
<%= link_to 'Back', linkedin_scarpers_path %>

app/views/linkedin_scarpers/get_profile_link.html.erb
 <%= form_tag linkedin_scarpers_path, :method => 'post' do %>
 <header>
<h4 class="title">Scarpe Profile</h4>
</header>
<section class="body">
<div class="body-inner">
 <div class="control-group" >
  <%= label_tag "Provide Linkedin Profile Link",nil,:class => "control-label" %> 
  <div class="controls">
  <%= text_field_tag "linkedin_scarper[profile_link]","", :class => "m-wrap large", :placeholder => "Profile Link" %>
  </div>
  </div>
   <div class="form-actions">
  <%= submit_tag "Scrape Profile",:id=>"submitButtonId" %>
  <% end %>
  </div>
</div>

app/views/linkedin_scarpers/index.html.erb
<%if @linkedin_scarpers.present? %>
  <div class="row-fluid">
                        <!-- START Basic Table -->
  <div class="span12 widget dark stacked">
    <header>
        <h4 class="title">Scarped  Profiles</h4>
        <!--/ END Toolbar -->
    </header>
    <section class="body">
      <div class="body-inner no-padding">
        <table class="table">
          <thead>
          <tr>
      <th class="table_header_text">First name</th>
      <th class="table_header_text">Last name</th>
      <th class="table_header_text">Name</th>
      <th class="table_header_text">Title</th>
      <th class="table_header_text">Location</th>
      <th class="table_header_text">Country</th>
      <th class="table_header_text">Industry</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @linkedin_scarpers.each do |linkedin_scarper| %>
      <tr>
        <td><%= linkedin_scarper.first_name %></td>
        <td><%= linkedin_scarper.last_name %></td>
        <td><%= linkedin_scarper.name %></td>
        <td><%= linkedin_scarper.title %></td>
        <td><%= linkedin_scarper.location %></td>
        <td><%= linkedin_scarper.country %></td>
        <td><%= linkedin_scarper.industry %></td>
          <td> <%= view_link (linkedin_scarper) %></td>
        <td> <%= delete_link (linkedin_scarper) %></td>
      </tr>
    <% end %>
   </tbody>
      </table>
    </div>
  </div>
  <%= paginate @linkedin_scarpers, :theme => "my_custom_theme" %>
<% else %>
No Profile Present!<br>
<% end %>
<br>

<%#= link_to 'New Linkedin scarper', new_linkedin_scarper_path %>

app/views/linkedin_scarpers/new.html.erb
<h1>New linkedin_scarper</h1>

<%= render 'form' %>

<%= link_to 'Back', linkedin_scarpers_path %>

app/views/linkedin_scarpers/show.html.erb
<div class="row-fluid">
                        <!-- START Basic Table -->
  <div class="span12 widget dark stacked">
    <header>
      <h4 class="title">Profile</h4>
      <!--/ END Toolbar -->
    </header>
    <section class="body">
      <div class="body-inner no-padding">
        <table class="table">
          <thead>
            <tr>

  <td><strong>First name:</strong></td>
  <td><%= @linkedin_scarper.first_name %></td>
</tr>

<tr>
  <td><strong>Last name:</strong></td>
  <td><%= @linkedin_scarper.last_name %></td>
</tr>

<tr>
  <td><strong>Name:</strong></td>
  <td><%= @linkedin_scarper.name %></td>
</tr>

<tr>
  <td><strong>Title:</strong></td>
  <td><%= @linkedin_scarper.title %></td>
</tr>

<tr>
  <td><strong>Location:</strong></td>
  <td><%= @linkedin_scarper.location %></td>
</tr>

<tr>
  <td><strong>Country:</strong></td>
  <%= @linkedin_scarper.country %>
</tr>

<tr>
  <td><strong>Industry:</strong></td>
  <td><%= @linkedin_scarper.industry %></td>
</tr>

<tr>
  <td><strong>Picture:</strong></td>
  <td><img src="<%= @linkedin_scarper.picture %>"</img></td>
</tr>

<tr>
  <td><strong>Skills:</strong></td>
  <td><%= @linkedin_scarper.skills %></td>
</tr>

<tr>
  <td><strong>Organization:</strong></td>
  <td><%#= @linkedin_scarper.organization %></td>
  <table>
  <th>  Name  </th>
  <th> Start Date</th>
  <th> End  date  </th>
  
  <td><% @linkedin_scarper.organization.each do |c|%>
  
  <tr>
  <td><%=c[:name]%></td>&nbsp
  <td>&nbsp<%=c[:start_date]%></td>
  <td><%=c[:end_date]%></td>
  </tr>
  <% end  %>
  </table>
</tr>

<tr>
  <td><strong>Education:</strong></td>
  <td><%#= @linkedin_scarper.education %></td>
  <table>
  <th>  Name  </th>
  <th>Description</th>
  <th>period   </th>
  
  <td><% @linkedin_scarper.education.each do |c|%>
  
  <tr>
  <td><%=c[:name]%></td>&nbsp
  <td><%=c[:description]%></td>
  <td><%=c[:period]%></td>
  
  </tr>
  <% end  %>
  </table>
</tr>

<tr>
  <td><strong>Websites:</strong></td>
  <td><%= @linkedin_scarper.websites %></td>
  
</tr>

<tr><br>
  <td><strong>Groups:</strong></td>
  <td><%#= @linkedin_scarper.groups %></td>
  <table>
  <th>  Name  </th>
  <th>Link</th>
  
  <td><% @linkedin_scarper.groups.each do |c|%>
  
  <tr>
  <td><%=c[:name]%></td>&nbsp
  <td><%=c[:link]%></td>
  
  </tr>
  <% end  %>
  </table>
</tr>

<tr>
  <td><strong>Languages:</strong></td>
  <td><%#= @linkedin_scarper.languages %></td>
  <table>
  <th>  Name  </th>
  <th></th>
  <th>Link</th>
  
  <td><% @linkedin_scarper.languages.each do |c|%>
  
  <tr>
  <td><%=c[:name]%></td>&nbsp
  <td><%=c[:link]%></td>
  
  </tr>
  <% end  %>
  </table>
</tr>

<tr>
  <td><strong>Certifications:</strong></td>
  <td><%= @linkedin_scarper.certifications %></td>
</tr>

<tr>
  <td><strong>Current companies:</strong></td>
  <table>
  <th>  Title </th>
  <th>  Company  </th>
  <th> Start date</th>
  <th> End  Date  </th>
  <th>Linkedin_company_url </tf>
  <th>Url</th>
  <th>Type</th>
  <th>Company  Size</th>
  <th>Type</th>
  <th>Address</th>
  <th>founded</th>
  
  <td><%  @linkedin_scarper.current_companies.each do |c|%>
  
  <tr>
  <td><%=c[:title]%></td>
  <td><%=c[:company]%></td>
  <td><%=c[:start_date]%></td>
  <td><%=c[:end_date]%></td>
  <td><%=c[:linkedin_company_url]%></td>
  <td><%=c[:url]%></td>
  <td><%=c[:type]%></td>
  <td><%=c[:company_size]%></td>
  <td><%=c[:type]%></td>
  <td><%=c[:founded]%></td>
  </tr>
  <% end  %>
  </table>
</tr>

<tr>
  <td><strong>Past companies:</strong></td>
  <td><%= @linkedin_scarper.past_companies %></td>
</tr>

<tr>
  <td><strong>Recommended visitors:</strong></td>
  <table>
  <th>  Link </th>
  <th>  Name  </th>
  <th> Title</th>
  <th> Company  </th>
  
  <td><% @linkedin_scarper.recommended_visitors.each do |c|%>
  
  <tr>
  <td><%=c[:link]%></td>
  <td><%=c[:name]%></td>
  <td><%=c[:title]%></td>
  <td><%=c[:company]%></td>
  </tr>
  <% end  %>
  </table>
  </td>
</tr>

</thead>
        </table> 
      </div>
    </div>
  </div>
  <%= link_to 'Back', linkedin_scarpers_path %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>